Repository styleKey/back, pull requests merged in 2024-03, with the labels that each got.

#48 [#47] test 도메인 리팩터링
  src/main/java/com/thekey/stylekeyserver/test/controller/TestController.java
  src/main/java/com/thekey/stylekeyserver/test/dto/response/TestResultCreateResponse.java
  src/main/java/com/thekey/stylekeyserver/test/entity/TestQuestion.java
  src/main/java/com/thekey/stylekeyserver/test/entity/TestResultDetail.java
  src/main/resources/data/test.sql
Labels: refactoring

#50 [feat/#49] TestQuestionResponse ImageUrl 추가
  src/main/java/com/thekey/stylekeyserver/test/dto/response/TestQuestionResponse.java
Labels: refactoring

#60 Refact: Security에서 SecurityContextHolder -> @AuthenticationPrincipal로 로그인 유저 정보 가져올 수 있도록 변경
  src/main/java/com/thekey/stylekeyserver/auth/controller/UserController.java
  src/main/java/com/thekey/stylekeyserver/common/security/JwtConfig.java
  src/main/java/com/thekey/stylekeyserver/common/security/SecurityConfig.java
  src/main/java/com/thekey/stylekeyserver/oauth/token/AuthTokenProvider.java
Labels: bug, refactoring

#62 Feat/#61 공용 컴포넌트 및 예외 처리
  src/main/java/com/thekey/stylekeyserver/common/dto/CreateResponse.java
  src/main/java/com/thekey/stylekeyserver/common/exception/ApiException.java
  src/main/java/com/thekey/stylekeyserver/common/exception/GlobalExceptionHandler.java
Labels: feat

#65 Feat/#63
  .github/ISSUE_TEMPLATE/feature.yml
  src/main/java/com/thekey/stylekeyserver/auth/controller/UserController.java
  src/main/java/com/thekey/stylekeyserver/auth/repository/UserRepository.java
  src/main/java/com/thekey/stylekeyserver/auth/service/UserService.java
  src/main/java/com/thekey/stylekeyserver/brand/controller/BrandAdminController.java
  src/main/java/com/thekey/stylekeyserver/common/annotation/ExactSize.java
  src/main/java/com/thekey/stylekeyserver/common/exception/ApiResponse.java
  src/main/java/com/thekey/stylekeyserver/common/exception/ErrorCode.java
  src/main/java/com/thekey/stylekeyserver/common/exception/GlobalExceptionHandler.java
  src/main/java/com/thekey/stylekeyserver/common/security/SecurityConfig.java
  src/main/java/com/thekey/stylekeyserver/common/validate/ListSizeValidator.java
  src/main/java/com/thekey/stylekeyserver/coordinatelook/controller/CoordinateLookAdminController.java
  src/main/java/com/thekey/stylekeyserver/coordinatelook/controller/CoordinateLookApiController.java
  src/main/java/com/thekey/stylekeyserver/item/controller/ItemAdminController.java
  src/main/java/com/thekey/stylekeyserver/item/controller/ItemApiController.java
  src/main/java/com/thekey/stylekeyserver/like/controller/LikeCoordinateLookController.java
  src/main/java/com/thekey/stylekeyserver/like/controller/LikeItemController.java
  src/main/java/com/thekey/stylekeyserver/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/thekey/stylekeyserver/oauth/service/CustomUserDetailsService.java
  src/main/java/com/thekey/stylekeyserver/test/ApiException.java
  src/main/java/com/thekey/stylekeyserver/test/TestErrorMessage.java
  src/main/java/com/thekey/stylekeyserver/test/controller/TestController.java
  src/main/java/com/thekey/stylekeyserver/test/dto/request/TestResultRequest.java
  src/main/java/com/thekey/stylekeyserver/test/dto/response/TestResultCreateResponse.java
  src/main/java/com/thekey/stylekeyserver/test/entity/TestResult.java
  src/main/java/com/thekey/stylekeyserver/test/service/TestResultService.java
  src/main/resources/data/test.sql
Labels: feat

#73 [feat/#72] feat: 템플릿 추가
  .github/ISSUE_TEMPLATE/etc.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feat

#75 Feat/#74 테스트 도메인 리팩터링
  src/main/java/com/thekey/stylekeyserver/test/dto/response/TestResultDetailResponse.java
  src/main/java/com/thekey/stylekeyserver/test/entity/TestAnswer.java
  src/main/java/com/thekey/stylekeyserver/test/repository/TestAnswerRepository.java
  src/main/java/com/thekey/stylekeyserver/test/service/TestResultService.java
Labels: refactoring

#77 [Feat/#76] 테스트 결과 생성 저장 로직 리팩터링
  build.gradle
  src/main/java/com/thekey/stylekeyserver/common/exception/ErrorCode.java
  src/main/java/com/thekey/stylekeyserver/common/exception/GlobalExceptionHandler.java
  src/main/java/com/thekey/stylekeyserver/test/controller/TestController.java
  src/main/java/com/thekey/stylekeyserver/test/dto/request/SaveTestResultRequest.java
  src/main/java/com/thekey/stylekeyserver/test/entity/TestAnswer.java
  src/main/java/com/thekey/stylekeyserver/test/entity/TestResult.java
  src/main/java/com/thekey/stylekeyserver/test/repository/TestAnswerRepository.java
  src/main/java/com/thekey/stylekeyserver/test/repository/TestResultRepository.java
  src/main/java/com/thekey/stylekeyserver/test/service/TestResultService.java
Labels: refactoring

#79 [feat/#78] refactor: TestAnswerDetail 엔티티 안에 있는 StylePoint 지연로딩 수정
  src/main/java/com/thekey/stylekeyserver/test/repository/TestAnswerRepository.java
Labels: refactoring

#84 [Feat/#83] https로 swagger 접속시 cors 에러 해결
  src/main/java/com/thekey/stylekeyserver/auth/entity/User.java
  src/main/java/com/thekey/stylekeyserver/swagger/SwaggerConfig.java
Labels: fix, refactoring

#82 최근 본 아이템 조회 기능
  src/main/java/com/thekey/stylekeyserver/auth/controller/UserController.java
  src/main/java/com/thekey/stylekeyserver/common/redis/RedisService.java
  src/main/java/com/thekey/stylekeyserver/item/controller/ItemApiController.java
  src/main/java/com/thekey/stylekeyserver/item/service/RecentlyViewedItemsService.java
  src/main/java/com/thekey/stylekeyserver/like/service/LikeCoordinateLookService.java
  src/main/java/com/thekey/stylekeyserver/like/service/LikeItemService.java
Labels: feat

#86 스타일포인트, 코디룩, 브랜드, 아이템 도메인 리팩토링
  src/main/java/com/thekey/stylekeyserver/brand/BrandErrorMessage.java
  src/main/java/com/thekey/stylekeyserver/brand/controller/BrandAdminController.java
  src/main/java/com/thekey/stylekeyserver/brand/controller/BrandApiController.java
  src/main/java/com/thekey/stylekeyserver/brand/dto/request/BrandRequest.java
  src/main/java/com/thekey/stylekeyserver/brand/service/BrandAdminService.java
  src/main/java/com/thekey/stylekeyserver/brand/service/BrandAdminServiceImpl.java
  src/main/java/com/thekey/stylekeyserver/category/CategoryErrorMessage.java
  src/main/java/com/thekey/stylekeyserver/category/controller/CategoryAdminController.java
  src/main/java/com/thekey/stylekeyserver/category/controller/CategoryApiController.java
  src/main/java/com/thekey/stylekeyserver/category/service/CategoryServiceImpl.java
  src/main/java/com/thekey/stylekeyserver/common/exception/ErrorCode.java
  src/main/java/com/thekey/stylekeyserver/common/exception/GlobalExceptionHandler.java
  src/main/java/com/thekey/stylekeyserver/common/redis/RedisService.java
  src/main/java/com/thekey/stylekeyserver/common/s3/S3ErrorMessage.java
  src/main/java/com/thekey/stylekeyserver/common/s3/service/S3Service.java
  src/main/java/com/thekey/stylekeyserver/coordinatelook/CoordinateLookErrorMessage.java
  src/main/java/com/thekey/stylekeyserver/coordinatelook/controller/CoordinateLookAdminController.java
  src/main/java/com/thekey/stylekeyserver/coordinatelook/dto/request/CoordinateLookRequest.java
  src/main/java/com/thekey/stylekeyserver/coordinatelook/service/CoordinateLookAdminService.java
  src/main/java/com/thekey/stylekeyserver/coordinatelook/service/CoordinateLookAdminServiceImpl.java
  src/main/java/com/thekey/stylekeyserver/image/service/ImageBatchService.java
  src/main/java/com/thekey/stylekeyserver/image/service/ImageService.java
  src/main/java/com/thekey/stylekeyserver/item/ItemErrorMessage.java
  src/main/java/com/thekey/stylekeyserver/item/controller/ItemAdminController.java
  src/main/java/com/thekey/stylekeyserver/item/service/ItemAdminService.java
  src/main/java/com/thekey/stylekeyserver/item/service/ItemAdminServiceImpl.java
  src/main/java/com/thekey/stylekeyserver/like/service/LikeCoordinateLookService.java
  src/main/java/com/thekey/stylekeyserver/like/service/LikeItemService.java
  src/main/java/com/thekey/stylekeyserver/stylepoint/StylePointErrorMessage.java
  src/main/java/com/thekey/stylekeyserver/stylepoint/controller/StylePointAdminController.java
  src/main/java/com/thekey/stylekeyserver/stylepoint/controller/StylePointApiController.java
  src/main/java/com/thekey/stylekeyserver/stylepoint/service/StylePointAdminServiceImpl.java
Labels: refactoring

#89 관리자페이지 페이징 처리 추가
  src/main/java/com/thekey/stylekeyserver/brand/controller/BrandAdminController.java
  src/main/java/com/thekey/stylekeyserver/brand/dto/response/BrandPageResponse.java
  src/main/java/com/thekey/stylekeyserver/brand/service/BrandAdminService.java
  src/main/java/com/thekey/stylekeyserver/brand/service/BrandAdminServiceImpl.java
  src/main/java/com/thekey/stylekeyserver/coordinatelook/controller/CoordinateLookAdminController.java
  src/main/java/com/thekey/stylekeyserver/coordinatelook/dto/response/CoordinateLookPageResponse.java
  src/main/java/com/thekey/stylekeyserver/coordinatelook/service/CoordinateLookAdminService.java
  src/main/java/com/thekey/stylekeyserver/coordinatelook/service/CoordinateLookAdminServiceImpl.java
  src/main/java/com/thekey/stylekeyserver/item/controller/ItemAdminController.java
  src/main/java/com/thekey/stylekeyserver/item/dto/response/ItemPageResponse.java
  src/main/java/com/thekey/stylekeyserver/item/repository/ItemRepository.java
  src/main/java/com/thekey/stylekeyserver/item/service/ItemAdminService.java
  src/main/java/com/thekey/stylekeyserver/item/service/ItemAdminServiceImpl.java
Labels: feat

#92 더미 데이터 추가
  src/main/java/com/thekey/stylekeyserver/database/DataSourceConfig.java
  src/main/resources/data.sql
  src/main/resources/data/category.sql
  src/main/resources/data/style-point.sql
  src/main/resources/data/test.sql
Labels: refactoring, etc
